# Generated by Django 4.1.1 on 2022-09-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo", name="due_date", field=models.DateField(auto_now=True),
        ),
    ]
