# Generated by Django 4.1.1 on 2022-09-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0002_todo_due_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="todo", name="due_date",),
        migrations.AddField(
            model_name="todo",
            name="memo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
